name: Lint and Test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Validate Code
        run: |
          npm ci
          npm run lint
          npm run check

      - name: Install Playwright
        run: |
          npx playwright install-deps
          npx playwright install

      - name: Test
        run: |
          npm ci
          npm run test
